[package]
name = "load_gltf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy="0.10.1"
smooth-bevy-cameras="0.8.0"

[profile.dev]
opt-level = 1
